repos:
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: clang-format
      files: \.(cpp|h|cuh|cu|hpp)$
    - id: cpplint
      args: [--filter=-build/include_subdir --filter=-whitespace/indent]
      files: \.(cpp|h|cuh|cu|hpp)$