repos:
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.0
    hooks:
      - id: cpplint
        args: ["--filter=-whitespace/indent,-build/include_subdir"]
        files: \.(cpp|h|cuh|cu|hpp)$
