repos:
  - repo: https://github.com/cpplint/cpplint
    rev: master  # 或者指定你想要的版本
    hooks:
      - id: cpplint
        args: ["--filter=-whitespace/indent,-build/include_subdir"]
        files: \.(cpp|h|cuh|cu|hpp)$
